/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AppDomain": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ConvexDeployment": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ConvexUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TheStakkApp": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}